/**
 * scripts/seed-curriculum.ts
 *
 * Seeder: Currícula Oficial de Salta — Nivel PRIMARIO (1er a 7mo Año)
 * Materias: Ciencias Naturales, Ciencias Sociales, Educación Artística,
 *           Educación Tecnológica, Lengua, Matemática
 *
 * Usage:  npx tsx scripts/seed-curriculum.ts
 */

import { neon } from '@neondatabase/serverless'
import * as dotenv from 'dotenv'
import { DEFAULT_JURISDICTION } from '../lib/curriculum-config'

dotenv.config({ path: '.env.local' })

const sql = neon(process.env.DATABASE_URL!)

interface CurriculumEntry {
  jurisdiccion?: string
  nivel: 'Primario' | 'Secundario' | 'Superior'
  materia: string
  grado: string
  eje: string
  temas: string[]
}

// ─────────────────────────────────────────────────────────────────────────────
// DATA — Nivel PRIMARIO
// ─────────────────────────────────────────────────────────────────────────────

const DATA: CurriculumEntry[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // CIENCIAS NATURALES
  // ══════════════════════════════════════════════════════════════════════════

  // 1er Año
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'1er Año', eje:'Los seres vivos: diversidad, unidad, interrelaciones y cambios', temas:['Diversidad Vegetal: Diferencias entre hierbas, arbustos y árboles (características del tallo).','Partes de la planta con flor: Estructuras y usos alimenticios (hojas, raíces, tallos, flores, frutos y semillas).','Diversidad Animal: Clasificación según hábitos de alimentación (carnívoros, herbívoros, omnívoros).','Morfología animal: Coberturas corporales (pelos, plumas, escamas) y tipos de miembros según desplazamiento.','Clasificación biológica inicial: Semejanzas y diferencias entre vertebrados e invertebrados.','El Cuerpo Humano: Características externas de la morfología corporal. Hábitos saludables de alimentación, higiene y recreación.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'1er Año', eje:'Los materiales y sus cambios', temas:['Sólidos y líquidos: Diferenciación de sus propiedades sensoriales y formas de manipulación.','Propiedades de los líquidos (viscosidad, color, transparencia, olor) y de los sólidos (permeabilidad, flexibilidad, elasticidad).','El aire en nuestro entorno: Reconocimiento de su presencia, peso y objetos que se mueven con aire.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'1er Año', eje:'Los fenómenos del mundo físico', temas:['Acciones mecánicas sobre los cuerpos: Estirar, doblar, comprimir, torcer, deformar y romper.','Resistencia de los objetos según el material del cual están conformados.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'1er Año', eje:'La Tierra, el Universo y sus cambios', temas:['El paisaje y sus componentes: Identificación de agua, aire, tierra, cielo y seres vivos.','Tipos de paisajes: Clasificación de paisajes urbanos, rurales y naturales (parques y reservas).','Fenómenos meteorológicos evidentes: Lluvia, niebla, nieve, granizo, nubes, viento y arco iris.','Tiempo atmosférico: Registro diario de condiciones del tiempo a través de pictogramas.'] },

  // 2do Año
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'2do Año', eje:'Los seres vivos: diversidad, unidad, interrelaciones y cambios', temas:['Diversidad de plantas: Adaptaciones a los ambientes terrestres, acuáticos y aeroterrestres. Ciclo de vida.','Dispersión de semillas: Mecanismos de dispersión por acción del viento, del agua y de los animales.','Diversidad de animales: Clasificación de animales ovíparos y vivíparos en ambientes terrestres, acuáticos y aeroterrestres.','Estructuras de desplazamiento de los animales según el ambiente en el cual viven.','El Cuerpo Humano: Procesos de crecimiento y desarrollo. Cambios en la dentición, talla y peso.','Prevención de enfermedades: Importancia de la vacunación, controles pediátricos y hábitos de higiene.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'2do Año', eje:'Los materiales y sus cambios', temas:['Propiedades ópticas de los materiales: Clasificación en transparentes, traslúcidos y opacos.','Comportamiento de los materiales frente a la luz y relación con los usos prácticos de los objetos cotidianos.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'2do Año', eje:'Los fenómenos del mundo físico', temas:['Movimiento de los cuerpos: Clasificación según la trayectoria (rectilínea, circular, en zigzag, combinada).','Trayectorias y rapidez. Modificaciones del movimiento por acción de fuerzas mecánicas.','La luz y las sombras: Fuentes luminosas naturales y artificiales. Producción de sombras según el movimiento de cuerpos y fuentes.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'2do Año', eje:'La Tierra, el Universo y sus cambios', temas:['Geoformas de la superficie terrestre: Llanuras, mesetas, montañas y valles. Semejanzas y diferencias.','Movimiento aparente del Sol: Relación con el ciclo del día y la noche.','El cielo diurno y nocturno: Observación de nubes, estrellas, la Luna y cambios de aspecto (fases lunares).'] },

  // 3er Año
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'3er Año', eje:'Los seres vivos: diversidad, unidad, interrelaciones y cambios', temas:['Interacciones biológicas en el ambiente: Relaciones alimentarias, cadenas alimentarias e interacciones de plantas y animales.','Dietas animales: Carnívoros, herbívoros (frugívoros, nectívoros, granívoros), insectívoros, hematófagos y omnívoros.','Adaptaciones de alimentación: Tipos de bocas, picos, dientes y comportamientos (hibernación, migración).','Sistemas del cuerpo humano: Localización y función general de órganos de sostén, digestivo, circulatorio, respiratorio, excretor y nervioso.','Salud y prevención: Consumo de agua potable y medidas de higiene en alimentos para evitar enfermedades endémicas.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'3er Año', eje:'Los materiales y sus cambios', temas:['Cambios de estado de la materia: Solidificación, fusión, vaporización y condensación por variación de la temperatura.','Mezclas de materiales: Mezclas homogéneas (soluciones) y heterogéneas.','Métodos de separación de mezclas: Tamización, filtración, decantación, imantación, evaporación.','Materiales de laboratorio: Uso adecuado de coladores, tamices, embudos, imanes y filtros.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'3er Año', eje:'Los fenómenos del mundo físico', temas:['Fenómenos sonoros: Fuentes de sonido, vibración de los cuerpos, propagación del sonido.','Propiedades del sonido: Intensidad (débiles y fuertes) y tono (graves y agudos). Instrumentos musicales.','Fenómenos térmicos: Equilibrio térmico, calentamiento y enfriamiento. Conductores y aislantes térmicos.','Medición de temperatura: El termómetro clínico y de laboratorio. Escalas de medición.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'3er Año', eje:'La Tierra, el Universo y sus cambios', temas:['Tiempo atmosférico: Clasificación convencional de fenómenos meteorológicos (lluvia, granizo, viento, nubes, brisas).','Instrumentos meteorológicos escolares: Introducción al pluviómetro, veleta, termómetro.','El Sistema Solar: Clasificación astronómica de astros (Sol como estrella, planetas, satélites, cometas).','Instrumentos de estudio espacial: Telescopios y satélites artificiales.','Movimientos terrestres y lunares: Frecuencia del movimiento aparente del sol y la luna. Relación con el día, mes y año. Puntos cardinales.'] },

  // 4to Año
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'4to Año', eje:'Los seres vivos: diversidad, unidad, interrelaciones y cambios', temas:['Diversidad de ambientes aeroterrestres: Temperatura, clima, suelo, vegetación y fauna de Puna, selva y bosque chaqueño.','Ambientes del pasado: Fósiles como registros de seres vivos que habitaron la región. Extinción de dinosaurios.','Dinámica del ambiente: El hombre como agente modificador (deforestación, urbanización) y conservación ambiental.','Clasificación de los seres vivos: Reinos biológicos (plantas, animales, hongos y microorganismos).','Estructuras de absorción, sostén, locomoción y polinización en plantas y animales aeroterrestres.','Hongos y microorganismos: Rol descomponedor en el suelo e interacciones biológicas. Uso del microscopio y lupa.','El cuerpo humano: Sistema osteo-artro-muscular (huesos largos, planos, cortos, articulaciones y músculos). Hábitos saludables.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'4to Año', eje:'Los materiales y sus cambios', temas:['Origen de los materiales: Materiales naturales (minerales) y manufacturados (cerámicos, plásticos).','Clasificación ambiental: Recursos renovables y no renovables, reciclables y biodegradables.','Propiedades físicas de los materiales: Conducción térmica, conducción eléctrica y propiedades magnéticas.','Familias de materiales: Metales, cerámicos y plásticos. Regularidades, obtención de materiales y aplicaciones tecnológicas.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'4to Año', eje:'Los fenómenos del mundo físico', temas:['Fuerzas que actúan a distancia: Fenómenos magnéticos (polos de un imán, atracción, repulsión) y electrostáticos.','El campo magnético terrestre: Funcionamiento de la brújula y magnetismo de la Tierra.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'4to Año', eje:'La Tierra, el Universo y sus cambios', temas:['La Tierra como cuerpo cósmico: Forma del planeta, dimensiones y movimiento de rotación terrestre.','La Tierra como sistema: Interrelación entre los subsistemas (Geosfera, Hidrosfera, Atmósfera y Biosfera).','La Geosfera: Estructura interna (núcleo, manto, corteza). Dinámica tectónica: Deriva continental, Pangea, volcanes y terremotos.'] },

  // 5to Año
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'5to Año', eje:'Los seres vivos: diversidad, unidad, interrelaciones y cambios', temas:['Ambientes acuáticos y de transición: Clasificación (continentales, lóticos, lénticos, oceánicos, dulceacuícolas, marinos).','Biodiversidad acuática: Plantas hidrófitas (flotantes, sumergidas, arraigadas), peces y microorganismos adaptados.','El cuerpo humano y la nutrición: Procesos y órganos principales de los sistemas digestivo, respiratorio, circulatorio y excretor.','Alimentación y salud: Composición nutricional de los alimentos, requerimientos calóricos, dieta equilibrada.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'5to Año', eje:'Los materiales y sus cambios', temas:['Los líquidos como disolventes: El agua como solvente universal.','Sistemas dispersos: Solutos y solventes en soluciones líquidas. Clasificación en diluidas y concentradas.','Solubilidad: Efecto de la temperatura, concentración, agitación en la solubilidad y relación con la contaminación hídrica.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'5to Año', eje:'Los fenómenos del mundo físico', temas:['La luz y su comportamiento: Propagación rectilínea de la luz y fenómeno de reflexión (espejos planos y curvos).','Descomposición espectral de la luz blanca en los colores del arco iris.','El sonido: Caracterización física de propiedades acústicas como el timbre y la altura.','Hidrostática y gravedad: Acción del peso en caída libre y el principio de flotación de los cuerpos (empuje).'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'5to Año', eje:'La Tierra, el Universo y sus cambios', temas:['La Hidrosfera: Estructura, abundancia de agua y tipos de agua (superficial, subterránea, congelada, atmosférica, oceánica).','El ciclo del agua: Dinámica de cambios de estado continuo del agua y su relación con los otros subsistemas.','Importancia ambiental: El agua como recurso natural indispensable para la salud, erosión hídrica e inundaciones.'] },

  // 6to Año
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'6to Año', eje:'Los seres vivos: diversidad, unidad, interrelaciones y cambios', temas:['Niveles de organización biológica: Celular, tisular, de órganos, de aparatos, de individuo, población, comunidad, ecosistema y biosfera.','La célula como unidad de vida: Teoría celular, estructuras comunes (membrana, citoplasma, material genético) y organelas.','Diferencias celulares: Célula animal y vegetal. Organismos unicelulares y pluricelulares especializados.','Nivel de Ecosistema: Componentes bióticos y abióticos de ecorregiones de Salta.','Relaciones tróficas: Redes y cadenas alimentarias, flujo de materia y energía. Productores, consumidores y descomponedores.','El hombre como modificador del ecosistema: Explotación minera, deforestación, contaminación del aire y del suelo.','El cuerpo humano y la relación: Estructura y funcionamiento de los sistemas nervioso central y periférico frente a estímulos.','Función de reproducción humana: Pubertad, preadolescencia, cambios anatómicos y fisiológicos del sistema reproductor masculino y femenino.','Salud reproductiva: Educación sexual integral, cuidado de la intimidad, infecciones de transmisión sexual (ITS) y prevención.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'6to Año', eje:'Los materiales y sus cambios', temas:['El aire como mezcla gaseosa: Propiedades de los gases (expansibilidad, compresibilidad, peso, volumen indefinido).','Contaminación atmosférica: Agentes contaminantes del aire, gases tóxicos y medidas de seguridad.','Transformaciones químicas: Procesos de oxidación rápida (combustión) y lenta (corrosión). Papel del oxígeno como comburente.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'6to Año', eje:'Los fenómenos del mundo físico', temas:['Energía: Fuentes (renovables, no renovables) y formas de energía. Transformación y degradación en la vida cotidiana.','Corriente eléctrica: Circuitos eléctricos simples. Componentes (generador, conductor, resistencia, interruptor).','Asociación de resistencias: Circuitos en serie y en paralelo. Precauciones en el uso domiciliario de electricidad.','Calor como transferencia energética: Mecanismos de conducción, convección y radiación. Dilatación de gases y equilibrio térmico.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'6to Año', eje:'La Tierra, el Universo y sus cambios', temas:['La Atmósfera: Estructura, capas constituyentes y composición gaseosa. Importancia de la capa de ozono como filtro UV.','Tiempo atmosférico y clima: Variables meteorológicas (presión, humedad, temperatura) y fenómenos (rayos, viento, precipitaciones).','Efecto invernadero: Causas y consecuencias del calentamiento global por emisiones gaseosas.','El Sistema Solar: Clasificación astronómica de planetas, satélites y planetas enanos.','Movimientos terrestres: Traslación y eje de inclinación en la determinación de las estaciones anuales.'] },

  // 7mo Año
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'7mo Año', eje:'Los seres vivos: diversidad, unidad, interrelaciones y cambios', temas:['La nutrición como proceso integrado: Relación entre digestión (nutrientes), respiración (oxígeno), circulación (transporte) y excreción (desechos).','Trastornos alimentarios y salud: Bulimia, anorexia, obesidad, desnutrición. Dieta equilibrada.','Nutrición autótrofa: Proceso de fotosíntesis, obtención de materia orgánica y liberación de oxígeno.','Respiración celular: Intercambio gaseoso celular, obtención de energía a partir de glucosa en autótrofos y heterótrofos.','Ecosistemas globales: Flujo de energía y ciclos de la materia. El ciclo biogeoquímico del carbono.','Alteración en la dinámica ecosistémica por desaparición y/o introducción de especies exóticas en las tramas tróficas.','Reproducción humana y sexualidad: Dimensiones biológica, psicológica, afectiva, social y ética. Infecciones de transmisión sexual (VIH-SIDA).'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'7mo Año', eje:'Los materiales y sus cambios', temas:['Estructura atómica de la materia: Átomos y partículas subatómicas (neutrones, protones, electrones).','Modelo cinético corpuscular: Movimiento térmico, fuerzas de atracción y repulsión en la explicación de sólidos, líquidos y gases.','Separación de mezclas complejas: Uso de propiedades de la materia (densidad, imantación, tamaño, decantación, centrifugación).','Contaminación ambiental química: Impacto de metales pesados, herbicidas e insecticidas en el suelo y el agua.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'7mo Año', eje:'Los fenómenos del mundo físico', temas:['Física mecánica y termodinámica: Concepto de energía cinética y potencial en sistemas mecánicos.','Nociones fundamentales: Principio de conservación de la energía, transformación y degradación de la misma.','Trabajo y calor como formas de transferencia y variación de la energía en procesos mecánicos.'] },
  { nivel:'Primario', materia:'Ciencias Naturales', grado:'7mo Año', eje:'La Tierra, el Universo y sus cambios', temas:['Recursos naturales terrestres: Clasificación de recursos hídricos, mineros, biológicos y fósiles.','Sostenibilidad planetaria: Uso racional, renovación y reutilización de recursos. Energías alternativas (eólica, solar, biomasa).'] },

  // ══════════════════════════════════════════════════════════════════════════
  // CIENCIAS SOCIALES
  // ══════════════════════════════════════════════════════════════════════════

  // 1er Año
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'1er Año', eje:'Las Sociedades y los Espacios Geográficos', temas:['Elementos naturales y sociales: Componentes de paisajes cercanos y lejanos (agua, relieve, vegetación, construcciones).','Elementos que favorecen la producción de bienes: Uso de recursos naturales como agua y suelo en el espacio rural.','Formas de organización de los espacios rurales: Actividades agropecuarias y de subsistencia orientadas al autoconsumo.','Paisajes urbanos: Trabajos, condiciones de vida de los trabajadores y servicios en ciudades pequeñas y grandes.','Servicios públicos y privados: Prestación de servicios esenciales (comercio, abastecimiento de agua, alumbrado público).','Nociones espaciales: El mapa mental, orientación y lateralidad. Croquis sencillos en salidas y paseos.'] },
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'1er Año', eje:'Las Sociedades a través del tiempo', temas:['Sociedades indígenas en la región: Diaguitas (montaña, sedentarios) y Tobas (monte, nómades). Ubicación, economía y vida cotidiana.','Vida cotidiana de las familias aborígenes: Organización familiar, roles de hombres, mujeres y niños, ritos, viviendas, vestimenta.','El trabajo con las Efemérides: Rescate de la figura de próceres y personajes destacados de la historia local y nacional.'] },
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'1er Año', eje:'Las actividades humanas y la organización social', temas:['Necesidades propias y espacios de recreación: La plaza hoy en contraste con el patio central diaguita y el campamento chaqueño.','Necesidades colectivas: La escuela como respuesta institucional. Educación sistemática actual vs. asistemática indígena.','El rol educador de los ancianos y padres en los pueblos originarios de Salta.'] },

  // 2do Año
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'2do Año', eje:'Las Sociedades y los Espacios Geográficos', temas:['Los espacios urbanos como productores de bienes industriales: Formas de organización en base a actividades industriales.','Procesos de producción artesanal e industrial: Trabajos, trabajadores, tecnologías y división de tareas.','Necesidades que cubre el servicio de transporte: Vinculación entre el espacio rural y urbano.','Sistemas y medios de transporte: Flujos de personas y mercancías, cobertura y accesibilidad.','Nociones espaciales: Orientación, lateralidad y estimación de distancias reales con pasos o croquis.'] },
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'2do Año', eje:'Las sociedades a través del tiempo', temas:['Sociedad colonial en la región: Siglos XVI-XVII (conquista y fundación) y siglo XVIII (Virreinato del Río de la Plata).','Grupos sociales coloniales: Vida cotidiana y roles de blancos, indígenas, mestizos y esclavos.','Viviendas, vestimentas, transportes y costumbres en el pasado colonial en contraste con el presente.','Conflictos resultantes de la desigualdad social y derechos en la época colonial.','El trabajo con las Efemérides: Noción de tiempo histórico a través de la vida de próceres (Güemes, Belgrano, San Martín).'] },
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'2do Año', eje:'Las actividades humanas y la organización social', temas:['Cambios en las prácticas sociales: Celebraciones, ritos y costumbres del pasado y del presente.','Sociedades indígenas ante la presencia española: El cambio de hábitos alimentarios y el impacto ambiental de la conquista.','Las organizaciones indígenas en la actualidad y sus reclamos territoriales e identitarios.'] },

  // 3er Año
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'3er Año', eje:'Las Sociedades y los Espacios Geográficos', temas:['Relaciones sociales y económicas entre áreas rurales y urbanas: Flujo de materias primas y bienes manufacturados.','Circuitos productivos regionales: Etapas agraria, comercial e industrial (casos de la leche, jugos o chocolate).','Trabajadores, tecnologías y problemáticas (sequías, heladas, inundaciones) en las distintas etapas del circuito.','La vida social en diversos contextos: Tamaño, fisonomía y función de ciudades (comercial, industrial, turística).','Nociones espaciales: Ubicación, orientación y desplazamientos utilizando los puntos cardinales, planos y croquis.'] },
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'3er Año', eje:'Las sociedades a través del tiempo', temas:['La Sociedad Criolla en la región: Revolución de Mayo de 1810, cambios y permanencias políticas, sociales y económicas.','Salta como escenario de guerra: La época de Güemes y el impacto de las guerras de independencia en la vida cotidiana.','Consecuencias de la guerra para los distintos grupos sociales: Levas forzosas, contribuciones económicas y movilidad social.','El trabajo con las Efemérides: Línea de tiempo, actores individuales y colectivos de la independencia.'] },
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'3er Año', eje:'Las actividades humanas y la organización social', temas:['El sistema político hoy: Instituciones y organizaciones políticas del medio local, provincial y nacional.','Conflictos entre diversos grupos en democracia y su resolución a través del diálogo y el consenso.','El sistema político municipal histórico: El Cabildo, funciones y conflictos (1820: suspensión de cabildos).','La municipalidad hoy: Estructura, funciones del intendente, ordenanzas y resolución de problemáticas locales.'] },

  // 4to Año
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'4to Año', eje:'Las Sociedades y los Espacios Geográficos', temas:['Salta en la Argentina: División política de la República Argentina. Localización y límites de la provincia de Salta.','Departamentos y municipios de la provincia de Salta: Localización y funciones de las localidades cabeceras.','Diversidad ambiental en Salta: Ambientes de la Puna, Cordillera Oriental (valles y quebradas), Sierras Subandinas y Chaco Salteño.','Relación sociedad-naturaleza: El relieve, cursos fluviales, condiciones climáticas y biomas como recursos valorados.','Problemas ambientales en Salta: Deforestación, inundaciones, pérdida de biodiversidad. Actores implicados (Estado, comunidad, ONGs).','Conservación del ambiente: Sistema Provincial de Áreas Protegidas (SIPAP) y Parques Nacionales en Salta.','Actividades productivas y calidad de vida en ámbitos rurales: Circuitos agropecuarios (caso de la vid en valles calchaquíes).','Condiciones de vida en ámbitos urbanos de la provincia: Acceso a servicios básicos, transportes y conectividad.','Manejo cartográfico: Símbolos, escalas, coordenadas geográficas, altimetrías y planos urbanos.'] },
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'4to Año', eje:'Las sociedades a través del tiempo', temas:['Etapa indígena prehispánica: Cazadores-recolectores del Chaco, agricultores de montaña (diaguitas) y el Imperio Inca.','Aprovechamiento de recursos, organización social, autoridad, jerarquías y cosmovisiones indígenas.','La Etapa Colonial: Expansión europea, llegada de los conquistadores y el rito de fundación de ciudades en el NOA.','El espacio peruano: Potosí como polo económico, mita, encomienda, comercialización de mulas y mano de obra indígena.','Resistencia y rebeliones indígenas en el NOA frente al dominio español (rebeliones calchaquíes y Pedro Bohorquez).','Los cambios del siglo XVIII: Creación de la Intendencia de Salta del Tucumán y la fundación de Orán.','La Etapa Criolla (1ª parte): La Revolución de Mayo en Salta, luchas de la independencia y el papel de Güemes y sus gauchos.'] },
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'4to Año', eje:'Las actividades humanas y la organización social', temas:['El sistema político: Niveles de gobierno nacional, provincial y municipal. División de poderes (Ejecutivo, Legislativo, Judicial).','Constitución de la Provincia de Salta: Estructura, derechos, deberes y garantías de los habitantes.','La diversidad cultural en Salta actual: Los pueblos originarios hoy (Wichí, Chorote, Toba, Kolla, Diaguita-calchaquí).','Identidad y derechos: Costumbres, lenguas maternas, reclamos territoriales e instituciones de defensa de las comunidades.'] },

  // 5to Año
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'5to Año', eje:'Las Sociedades y los Espacios Geográficos', temas:['El territorio de la República Argentina: Delimitación política del país, provincias, capitales, límites y fronteras.','Ciudad Autónoma de Buenos Aires (CABA): Su estatus de Capital Federal de la República.','Diversidad ambiental de la Argentina: Relieve (montañas, mesetas, llanuras), climogramas, biomas y ambientes resultantes.','Los recursos naturales en la Argentina: Recursos renovables, no renovables y perpetuos. Manejo sustentable vs. explotacionista.','El Sistema Nacional de Áreas Protegidas: Parques Nacionales, reservas y monumentos naturales en Argentina.','Problemas ambientales nacionales: Erosión del suelo, contaminación del agua y aire, deforestación. Multicausalidad.','Fenómenos naturales y catástrofes sociales: Sismos, vulcanismo, inundaciones y sequías en Argentina. Riesgo y vulnerabilidad.','Ámbitos rurales argentinos: Circuitos agroindustriales regionales (materia prima, procesamiento, comercialización y tecnologías).','Ámbitos urbanos argentinos: Clasificación de ciudades según tamaño y funciones (comercial, industrial, turística, político-administrativa).','Condiciones de vida de la población: Necesidades básicas insatisfechas, censos de población e indicadores socioeconómicos.'] },
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'5to Año', eje:'Las sociedades a través del tiempo', temas:['La Etapa Criolla (Revolución y ensayos de gobierno): Antecedentes europeos y americanos de la Revolución de Mayo.','La Revolución de 1810 y el proceso de desintegración del Virreinato. Consecuencias de las guerras de independencia.','Las autonomías provinciales (1820-1850): El militarismo, surgimiento de caudillos, unitarios y federales.','La época de Rosas: Economía regional, la aduana de Buenos Aires, transportes y el control rosista.'] },
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'5to Año', eje:'Las actividades humanas y la organización social', temas:['El sistema político nacional: Poderes del Estado (Ejecutivo, Legislativo y Judicial) según la Constitución Nacional.','La Constitución Nacional: Estructura, declaraciones, derechos, deberes y garantías de los ciudadanos.','Derechos del Niño y del Adolescente: Su consagración en convenios internacionales y vigencia en la sociedad actual.','Participación democrática y resolución de conflictos sociales (ambientales, laborales) mediante el diálogo y la mediación.'] },

  // 6to Año
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'6to Año', eje:'Las Sociedades y los Espacios Geográficos', temas:['América Latina en el mundo: Mapa político, capitales, límites, fronteras y procesos de integración (MERCOSUR).','La diversidad ambiental de América Latina: Grandes conjuntos ambientales (selvas, desiertos, praderas, bosques y montañas).','Uso y manejo sustentable de los recursos naturales en el continente: Reservas de la biosfera y políticas ambientales.','Dinámica demográfica de la población argentina: Distribución, estructura por edad y sexo (pirámides de población).','Movimientos migratorios en Argentina: Migraciones internas y limítrofes, causas y consecuencias socioeconómicas.','Calidad de vida de la población: Indicadores socioeconómicos (salud, educación, empleo y vivienda).'] },
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'6to Año', eje:'Las sociedades a través del tiempo', temas:['La organización del Estado Nacional (1853-1880): Presidencias de Urquiza, Mitre, Sarmiento, Avellaneda.','La sanción de la Constitución Nacional de 1853: Debates, acuerdos y conflictos interprovinciales.','El modelo agroexportador (1880-1914): Inserción de la Argentina en la división internacional del trabajo como proveedora de materias primas.','La inmigración masiva y colonización agrícola: El ferrocarril, cambios demográficos, conventillos y urbanización acelerada.','La sociedad aluvial: Surgimiento de nuevos sectores sociales, la Unión Cívica Radical y el camino a la Ley Sáenz Peña de 1912.'] },
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'6to Año', eje:'Las actividades humanas y la organización social', temas:['Derechos Humanos: La Declaración Universal de los Derechos Humanos, análisis de su vigencia y violaciones en el pasado y presente.','Acuerdos internacionales con rango constitucional: Convenciones sobre discriminación, tortura y derechos de la mujer.','Los procesos de integración regional (MERCOSUR): Objetivos económicos, políticos y sociales de la integración.','Respeto y valoración de la diversidad cultural en las manifestaciones latinoamericanas contemporáneas.'] },

  // 7mo Año
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'7mo Año', eje:'Las Sociedades y los Espacios Geográficos', temas:['El espacio geográfico mundial: Relación naturaleza-sociedad. Ubicación absoluta (coordenadas) y relativa.','La Tierra y sus ambientes: Grandes cordilleras, llanuras y mesetas del planeta. Distribución climática mundial y climogramas.','Uso, valoración y apropiación de los recursos naturales a nivel global. El manejo sustentable y las energías alternativas.','Problemas ambientales de escala mundial: El calentamiento global, destrucción de bosques tropicales y contaminación oceánica.','Fenómenos naturales y desastres sociales: Dinámica de riesgo y vulnerabilidad social en catástrofes.','La población mundial: Distribución desigual (focos de concentración y desiertos demográficos), estructura y migraciones globales.','El proceso de urbanización mundial: Funciones de las ciudades globales, segregación socioespacial y fisonomía urbana actual.','Procesos productivos globales: Multinacionales, división internacional del trabajo y transportes transcontinentales.','Manejo cartográfico: Mapas de flujo, símbolos abstractos y variaciones de escalas.'] },
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'7mo Año', eje:'Las sociedades a través del tiempo', temas:['La crisis del 30 y sus consecuencias en Argentina: Caída del modelo agroexportador e inicio de la industrialización sustitutiva (ISI).','El Peronismo (1945-1955): El Estado de Bienestar, políticas de nacionalización, redistribución de riqueza, sindicatos y voto femenino.','Inestabilidad institucional (1955-1976): Gobiernos democráticos condicionados (Frondizi, Illia) y golpes militares.','Terrorismo de Estado y la última dictadura (1976-1983): La sistemática violación de derechos humanos, deuda externa y Guerra de Malvinas.','Restauración democrática (1983-actualidad): Gobiernos constitucionales, reformas constitucionales, neoliberalismo de los \'90 y crisis del 2001.','La memoria histórica: Juicio a las juntas, Madres y Abuelas de Plaza de Mayo, y los procesos de verdad y justicia en Argentina.'] },
  { nivel:'Primario', materia:'Ciencias Sociales', grado:'7mo Año', eje:'Las actividades humanas y la organización social', temas:['El sistema político actual: Rol de los partidos políticos, la participación ciudadana y el marco legal en democracia.','El sistema económico y división del trabajo: El teletrabajo, flexibilización laboral, la globalización y las multinacionales.','El sistema social y relaciones familiares: Nuevas formas de vinculación familiar, derechos de minorías y rechazo a la discriminación.'] },

  // ══════════════════════════════════════════════════════════════════════════
  // EDUCACIÓN ARTÍSTICA
  // ══════════════════════════════════════════════════════════════════════════

  { nivel:'Primario', materia:'Educación Artística', grado:'1er Año', eje:'Elementos y la práctica de los lenguajes artísticos', temas:['Artes Visuales: percepción sensorial, códigos específicos del lenguaje. Imágenes bidimensionales (dibujo, estampado, encolado, pintura) y tridimensionales (modelado, construcciones, móviles, relieves, ensamblados).','Danza (Alfabeto Expresivo): elementos (cuerpo, espacio, tiempo, ritmo). Imagen global y segmentada del propio cuerpo. Direcciones en el espacio, peso, apoyos, movimiento ligado-cortado.','Música: sonido-silencio. Cualidades sensoriales (altura, timbre, intensidad, duración). Relación de pares complementarios. Paisajes sonoros.','Teatro: estructura dramática (acción cotidiana e imaginaria, sujeto, roles conocidos, argumento, cuentos breves, relatos, imágenes, conflicto, entorno, espacio de representación).','Folklore: música (canciones folklóricas infantiles, instrumentos de percusión, carnavalito, candombe, figuras fundamentales). Literatura folclórica (cuentos y relatos). Folklore espiritual (juegos infantiles tradicionales).'] },
  { nivel:'Primario', materia:'Educación Artística', grado:'1er Año', eje:'Construcción de identidad y cultura', temas:['Artes Visuales: producciones propias y ajenas. Patrimonio cultural del entorno cercano (colores, formas, texturas). Artistas y creadores locales.','Danza: espectáculos y encuentros locales. Participar y valorar las diferentes manifestaciones corporales danzadas.','Música: patrimonio cultural local, manifestaciones de diversos estilos. Ámbitos culturales (salas, festivales, fiestas populares). Música y tecnologías (grabación). Repertorio patrio.','Teatro: manifestaciones teatrales del ámbito local, regional y nacional. Ámbitos teatrales convencionales.','Folklore: ornamentos. Folklore material: comidas y bebidas tradicionales.'] },

  { nivel:'Primario', materia:'Educación Artística', grado:'2do Año', eje:'Elementos y la práctica de los lenguajes artísticos', temas:['Artes Visuales: percepción, lenguaje visual a través de la exploración sensorial. Imágenes fijas y en movimiento, color emocional y simbólico. Bidimensión y tridimensión.','Danza: equilibrios estáticos con apoyos. Evocar y producir imágenes corporales. Noción de conjunto con objetos (sogas, lanas). Imitación, desplazamiento fundamental, dinámicas de movimiento.','Música: sonido como materia prima. Secuencia sonora. Percepción de sonido-silencio. Audición reflexiva. Clasificación de sonidos según material y origen.','Teatro: estructura dramática: acción, personajes reales e imaginarios, conflicto con el entorno, espacio del juego, transformaciones, circunstancias dadas, argumento.','Folklore: instrumentos musicales regionales y étnicos. Formas musicales: baguala, vidala, vidalita, chacarera. Danzas folklóricas tradicionales.'] },
  { nivel:'Primario', materia:'Educación Artística', grado:'2do Año', eje:'Construcción de identidad y cultura', temas:['Artes Visuales: producciones plásticas del entorno, artistas y creadores locales, patrimonio visual, exposiciones.','Danza: estilo y vestimenta de danzas folklóricas, regionales y latinoamericanas. Ritmo, secuencias rítmicas, la voz.','Música: interactuar con la música del entorno cercano, visitas a ámbitos culturales, ruedas de devoluciones.','Teatro: manifestaciones en la escuela, fiestas patrias, actos escolares. Espacios abiertos y no convencionales.','Folklore: ornamentos. Folklore material: comidas y bebidas tradicionales.'] },

  { nivel:'Primario', materia:'Educación Artística', grado:'3er Año', eje:'Elementos y la práctica de los lenguajes artísticos', temas:['Artes Visuales: color, textura, forma y espacio. Imágenes grupales. Bidimensión y tridimensión. Herramientas, soportes, tecnología digital.','Danza (Alfabeto Expresivo): forma tridimensional del cuerpo, respiración, tono muscular, calidades de movimiento, equilibrios y desequilibrios dinámicos, secuencias.','Música: sonidos del entorno, grafía analógica, relatos sonoros. Cuerpo como fuente sonora. Estructura formal binaria. Cancionero patrio. Texturas monódicas y polifónicas.','Teatro: estructura dramática: acción e intención, personajes, conflicto, entorno, circunstancias, argumento, espacio escénico. Juegos de comunicación, mímicas, pantomimas.','Folklore: canciones populares, copla, chaya, tonada. Danzas folklóricas (gato cuyano, gato porteño, chacarera doble). Refranes, adivinanzas.'] },
  { nivel:'Primario', materia:'Educación Artística', grado:'3er Año', eje:'Construcción de identidad y cultura', temas:['Artes Visuales: circuito de circulación de la obra, símbolos y rasgos de la comunidad, espectáculos.','Danza: proceso creativo, espectáculos, coreografías sencillas, rol expresivo.','Música: integrar patrimonios locales a la escuela, interpretar canciones tradicionales, música de pueblos originarios (chorotes, tobas, etc.).','Teatro: ámbitos de producción, partes de un teatro, artistas teatrales, relación con el cine y medios.','Folklore: folklore espiritual (juegos tradicionales como el pato, sortija, carreras).'] },

  { nivel:'Primario', materia:'Educación Artística', grado:'4to Año', eje:'Elementos y la práctica de los lenguajes artísticos', temas:['Artes Visuales: percepción, imagen como fenómeno artístico. Códigos específicos (imagen literal y metafórica, contraste, forma, figura y fondo, composición, encuadre, escala).','Danza: alineación, tono muscular, apoyos, nociones y diseños espaciales, locomoción, peso del cuerpo, objetos. Figuras de danzas, velocidad, duración, ritmo, comunicación.','Música: escala tonal, motivos melódicos, tónica y dominante. Ritmo: malambo. Estructura formal, texturas. Instrumentos convencionales, autóctonos, folclóricos.','Teatro: recepción, observación, escucha, atención, concentración. Estructura dramática: personaje, acción, secuencia, conflicto, entorno, argumento.','Folklore: cantares (villancicos, rondas), instrumentos musicales folclóricos criollos (bombo en malambo). Danzas: escondido, bailecito, pala pala, malambo.'] },
  { nivel:'Primario', materia:'Educación Artística', grado:'4to Año', eje:'Construcción de identidad y cultura', temas:['Artes Visuales: producciones de su contexto y circuitos de circulación.','Danza: proceso creativo, contexto social, manifestaciones, patrimonio regional.','Música: mundo sonoro local, contaminación sonora, pueblos originarios (rituales: baile del suri, pim pim), cancionero patrio (Himno a Güemes, Marcha a la Bandera).','Teatro: manifestaciones del ámbito local, regional, nacional. Ámbitos de producción, trabajadores, relación con el cine.','Folklore: folklore social (apodos y motes). Folklore material (vivienda, apero, vestimenta del gaucho). Juegos folclóricos: carrera de sortija.'] },

  { nivel:'Primario', materia:'Educación Artística', grado:'5to Año', eje:'Elementos y la práctica de los lenguajes artísticos', temas:['Artes Visuales: pintura, escultura, grabado, dibujo, cerámica, tapiz, instalaciones, fotografía. Encuadres, puntos de vista, composición, figura en plano y volumen.','Danza: elementos (cuerpo, espacio, tiempo, energía, creatividad). Calidades de movimiento, apoyos, caídas, peso, equilibrio, desequilibrio, saltos. Figuras de danzas.','Música: melodías en modo mayor, menor y pentatónico. Ritmo (cueca, zamba, gato, chaya, carnavalito). Texturas, canon. Instrumentos.','Teatro: recepción, observación, concentración. Estructura dramática: personajes, acción, secuencias, conflicto, argumento, tiempo de escena. Proyección de energía, voz.','Folklore: cancionero: letra y música de zambas, chacareras y cuecas. Instrumentos de acompañamiento. Danzas: remedio, cuando, arunguita, gato correntino. Leyendas regionales.'] },
  { nivel:'Primario', materia:'Educación Artística', grado:'5to Año', eje:'Construcción de identidad y cultura', temas:['Artes Visuales: circuitos de producción, significados simbólicos, contexto histórico.','Danza: conexión con el entorno, celebraciones cotidianas, análisis crítico de modelos corporales.','Música: mundo sonoro geográfico regional, leyendas. Canción patria con charango, guitarra, bombo, erke. ESI.','Teatro: producción en contexto, orígenes de las prácticas artísticas, trabajadores, medios masivos.','Folklore: folklore social y espiritual: celebraciones religiosas (patronales, misachicos, carnaval, Pachamama).'] },

  { nivel:'Primario', materia:'Educación Artística', grado:'6to Año', eje:'Elementos y la práctica de los lenguajes artísticos', temas:['Artes Visuales: pinturas, impresos, objetos, dibujos, esculturas, arquitectura, fotografía. Forma, color (valor, veladuras, sombras), luz, tramas, imágenes digitales.','Danza: ritmo interno, respiración, locomoción compuesta, caídas y recuperación, peso, apoyos. Figuras de danzas, parámetros temporales, unísono, sucesión, canon.','Música: melodías en diferentes estilos. Armonía (fórmulas cadenciales). Ritmo (comparsa, baguala, murga, candombe, milonga). Instrumentos de orquesta, acústicos, eléctricos, digitales.','Teatro: percepción analítica de elementos de la acción dramática. Estructura dramática: personajes, acción, conflicto, argumento, tiempo real y ficcional, espacio. TIC.','Folklore: instrumentos musicales etnográficos aborígenes, precolombinos. Danzas étnicas. Ritmos afro-rioplatenses: murga, candombe, milonga, tango. Danzas: sombrerito, gato encadenado, zamba, chamamé.'] },
  { nivel:'Primario', materia:'Educación Artística', grado:'6to Año', eje:'Construcción de identidad y cultura', temas:['Artes Visuales: contextos culturales, entorno natural e intervenciones estéticas, muestras.','Danza: relación entre contexto y hecho artístico, producciones de coreógrafos, análisis de modelos corporales.','Música: estilos, manifestaciones, música etnográfica, cancionero patrio (Himno Nacional, Himno a San Martín, Aurora). ESI.','Teatro: investigación de fenómenos culturales cercanos (corso, misachico, desfile, comparsa, Pachamama, Vía Crucis viviente).','Folklore: salidas de investigación, museos, destrezas criollas, celebraciones tradicionales.'] },

  { nivel:'Primario', materia:'Educación Artística', grado:'7mo Año', eje:'Elementos y la práctica de los lenguajes artísticos', temas:['Artes Visuales: trasposición, mecanismos de creación, percepción visual, abstracta y figurativa. Proporción, canon, relación áurea. Forma bi y tridimensional, contraste, luminosidad.','Danza (Alfabeto Expresivo): esquema corporal, alineación, respiración-sonido-movimiento, tono muscular, locomoción, caídas, recuperación. Figuras de danzas, simetría/asimetría.','Música: modos mayores, menores, pentatónicos, modos antiguos, polifonía. Armonía. Ritmos del folklore latinoamericano (saya, vals, polca, rumba, salsa, rock, blues). Ritmos árabes y orientales.','Teatro: instrumentos (cuerpo, voz, gestos cotidianos, exageraciones, calidades de movimiento, palabra). Procedimientos (improvisación, creación colectiva, montaje escénico, ensayo).','Folklore: el folklore: historia, orígenes del siglo XIX. Danzas tradicionales: Pericón Nacional (historia, vestuario, coreografía). Literatura folclórica: el gaucho, poemas gauchescos (Martín Fierro).'] },
  { nivel:'Primario', materia:'Educación Artística', grado:'7mo Año', eje:'Construcción de identidad y cultura', temas:['Artes Visuales: factores culturales, sociales y subjetivos. Contacto con artistas locales (plateros, tejedores, vestuaristas, realizadores audiovisuales). Muestras.','Danza: reflexión sobre intencionalidad discursiva, patrimonio latinoamericano, análisis crítico de modelos corporales.','Música: investigación de campo (tango, cueca, zamba, chamamé, chacarera, chaya, baguala, carnavalito), producciones audiovisuales, cancionero patrio.','Teatro: lectura de dramaturgos locales, estéticas contemporáneas, trabajadores teatrales (directores, dramaturgos, iluminadores, vestuaristas).','Folklore: hechos y fenómenos tradicionales del pueblo. Compositores y poetas (Bartolomé Hidalgo, José Hernández, Estanislao del Campo). Festivales folclóricos.'] },

  // ══════════════════════════════════════════════════════════════════════════
  // EDUCACIÓN TECNOLÓGICA
  // ══════════════════════════════════════════════════════════════════════════

  { nivel:'Primario', materia:'Educación Tecnológica', grado:'1er Año', eje:'Los procesos tecnológicos', temas:['Materiales de uso habitual: clasificación en naturales y transformados según su origen.','Los materiales para la construcción de diferentes objetos: propiedades (según los sentidos). Posibilidades y limitaciones de los materiales.','Transformación de los materiales extraídos de la naturaleza a través de operaciones: separar, batir, exprimir, moler o prensar.','Conformación de los materiales para elaborar los productos (modelado, estampado, embutido o corte).','Operaciones técnicas en los procesos tecnológicos. Secuencia temporal. Recursos. Las máquinas.','Procedimientos necesarios para utilizar máquinas en general, entre ellas el equipamiento multimedial e informático.'] },
  { nivel:'Primario', materia:'Educación Tecnológica', grado:'1er Año', eje:'Los medios técnicos', temas:['Procedimientos necesarios para realizar una tarea sin herramientas y con el apoyo de ella.','Análisis de herramientas identificando las partes que la conforman y los materiales que constituyen cada parte.','Diferentes herramientas del entorno: su uso según los materiales. Posibilidades de modificar alguna de sus partes.','Diseño de objetos (herramientas innovadas).','Técnicas básicas para el trabajo y manejo de herramientas. Elaboración de objetos sencillos.','Bocetos y croquis como herramientas de trabajo y comunicación.'] },
  { nivel:'Primario', materia:'Educación Tecnológica', grado:'1er Año', eje:'La reflexión sobre la tecnología, como proceso socio cultural: diversidad, cambios y continuidades', temas:['Las actividades cotidianas: su cambio a través del tiempo.','La producción artesanal e industrial: diferenciación. Sus cambios a través del tiempo (pan, dulce de leche, mermeladas, leche, etcétera).'] },

  { nivel:'Primario', materia:'Educación Tecnológica', grado:'2do Año', eje:'Los procesos tecnológicos', temas:['Materiales de uso habitual: clasificación general. Propiedades (según los sentidos). Características de los materiales en objetos, construcciones y productos del entorno cotidiano.','Conformación de los materiales mediante operaciones de encastrado, unión, anudado o apilados.','Procesos tecnológicos en serie: identificando las operaciones técnicas que intervienen y el orden en que se realizan.','Diseño, planificación y construcción de prototipos sencillos.'] },
  { nivel:'Primario', materia:'Educación Tecnológica', grado:'2do Año', eje:'Los medios técnicos', temas:['Análisis de las herramientas: zonas, función de cada una, materiales. Las partes que se vinculan con el cuerpo humano y las que actúan sobre el material.','Las herramientas: importancia en la realización de tareas. Clasificación según su utilidad (tomar, sujetar, contener, fijar o mover materiales).','Diseño de objetos (herramientas innovadas) para resolver situaciones concretas.','Bocetos y croquis como herramientas de trabajo y comunicación.'] },
  { nivel:'Primario', materia:'Educación Tecnológica', grado:'2do Año', eje:'La reflexión sobre la tecnología, como proceso socio cultural: diversidad, cambios y continuidades', temas:['Los oficios: su cambio a través del tiempo, en relación a las herramientas utilizadas, a los materiales y a las formas de realizar el trabajo.','Los nuevos oficios y profesiones en relación con la vestimenta, alimentación, comunicaciones.','Las herramientas a través del tiempo y los cambios sufridos según el avance de la tecnología.'] },

  { nivel:'Primario', materia:'Educación Tecnológica', grado:'3er Año', eje:'Los procesos tecnológicos', temas:['Procesos tecnológicos: operaciones de transporte de materiales, productos y/o personas, y de almacenamiento.','Alternativas para elevar, transportar y almacenar cargas.','Transformación de los materiales según su propiedad (dureza, flexibilidad, maleabilidad, ductilidad, permeabilidad).','Ciclo de vida de los productos. Importancia en los procesos tecnológicos.','Procesos tecnológicos: insumos, operaciones y medios técnicos. Secuencia de las operaciones en serie o en paralelo.'] },
  { nivel:'Primario', materia:'Educación Tecnológica', grado:'3er Año', eje:'Los medios técnicos', temas:['Análisis de herramientas según su uso en diferentes tareas. Clasificación.','Análisis de las partes de las herramientas. Movimientos de cada una de las partes. Similitudes y diferencias.','Diseño y construcción de herramientas (con uniones móviles) para resolver situaciones concretas.','Análisis de las técnicas empleadas. Las técnicas en la producción. Técnicas antiguas y técnicas modernas.','Bocetos y croquis como herramientas de trabajo y comunicación.'] },
  { nivel:'Primario', materia:'Educación Tecnológica', grado:'3er Año', eje:'La reflexión sobre la tecnología, como proceso socio cultural: diversidad, cambios y continuidades', temas:['El accionar tecnológico a través del tiempo: aspectos que cambian y que se conservan.','El impacto de la tecnología en los oficios y las profesiones.','El avance de la tecnología a través de los tiempos. Nuevas tecnologías que promueven nuevos conocimientos.'] },

  { nivel:'Primario', materia:'Educación Tecnológica', grado:'4to Año', eje:'Los processes tecnológicos', temas:['Los materiales. Origen. Los materiales en el tiempo. Propiedades: dureza, plasticidad, flexibilidad. Técnicas de conformación (moldeo, forja, estampación, laminación).','Etapas de los procesos de fabricación. Secuencia necesaria para la fabricación de artefactos.','La construcción de artefactos, anticipando y ordenando las operaciones, seleccionando las herramientas y procedimientos.','Los insumos materiales (recursos extraídos de la naturaleza o materiales con algún nivel de elaboración previa).','Los soportes de información. Los medios de comunicación. Tecnologías digitales de información.'] },
  { nivel:'Primario', materia:'Educación Tecnológica', grado:'4to Año', eje:'Los medios técnicos', temas:['Las herramientas: clasificación en simples y con mecanismos. Partes que conforman una herramienta. Movimientos de cada una de ellas.','Los mecanismos de las herramientas. Mecanismos básicos de transmisión y transformación de movimientos (polea, biela-manivela, leva, engranajes, cadena, palancas, tornillo).','Las máquinas: sus componentes (motor, mecanismo, bastidor, componente de seguridad); su funcionamiento.','Diseño y construcción de máquinas simples con un fin determinado.','Bocetos y croquis como herramientas de trabajo y comunicación.'] },
  { nivel:'Primario', materia:'Educación Tecnológica', grado:'4to Año', eje:'La reflexión sobre la tecnología, como proceso socio cultural: diversidad, cambios y continuidades', temas:['Los materiales a través de la historia y en las diferentes culturas.','Las herramientas a través de los tiempos. Los cambios socio-técnicos producidos.','El uso de las máquinas y las herramientas en procesos similares y contextos diferentes.'] },

  { nivel:'Primario', materia:'Educación Tecnológica', grado:'5to Año', eje:'Los procesos tecnológicos', temas:['Propiedades mecánicas de los materiales. Las estructuras: propiedades y clasificación.','Los procesos de recolección, transporte y distribución (provisión de agua, recolección de residuos, correo postal, transporte de granos).','Transformación, transporte y almacenamiento de los materiales en procesos de manufactura.','Los procesos de pequeña y gran escala de un mismo producto: semejanzas y diferencias.','La energía en diversos procesos, como calentar o enfriar, batir o mezclar.'] },
  { nivel:'Primario', materia:'Educación Tecnológica', grado:'5to Año', eje:'Los medios técnicos', temas:['Los mecanismos básicos de transmisión y transformación de movimientos. Los engranajes, las poleas, las levas, los cigüeñales.','Los motores: características. Su empleo. Ventajas y desventajas de su uso.','Control manual y control automático: características y diferencias.','Diseño de máquinas con un fin determinado. Construcción de las mismas.'] },
  { nivel:'Primario', materia:'Educación Tecnológica', grado:'5to Año', eje:'La reflexión sobre la tecnología, como proceso socio cultural: diversidad, cambios y continuidades', temas:['Los cambios socio-técnicos en la vida cotidiana y en los diversos lugares de trabajo. El paso del uso de herramientas al uso de máquinas.','El transporte, almacenamiento y la recolección de materiales a través del tiempo y en diferentes contextos.','Las modificaciones de los aspectos sociales, técnicos y económicos de las actividades en contexto de trabajo.'] },

  { nivel:'Primario', materia:'Educación Tecnológica', grado:'6to Año', eje:'Los procesos tecnológicos', temas:['Los insumos: materia, energía e información. Transformación, transporte, distribución y almacenamiento.','La energía: formas y fuentes. Circuitos eléctricos simples: funcionamiento y elementos. Circuito en serie y en paralelo.','Los motores eléctricos o de combustión: la función de motorizar las máquinas.','Líneas de producción. Distribución espacial de máquinas. Producción en serie. Cadenas de montaje.','Tareas de control en relación con la calidad, la cantidad de los productos y la revisión de los desperdicios.'] },
  { nivel:'Primario', materia:'Educación Tecnológica', grado:'6to Año', eje:'Los medios técnicos', temas:['Sistemas manuales y sistemas automáticos: diferencias y similitudes.','Los sistemas: flujos de materia, energía e información.','Los dispositivos de control. Las válvulas. Diagrama de bloques.','Aproximación a algunas características de los sensores y/o temporizadores.','Las estructuras y el diseño de máquinas, seleccionando el tipo de motor y el control y la regularidad de movimientos.','Bocetos y croquis como herramientas de trabajo y comunicación.'] },
  { nivel:'Primario', materia:'Educación Tecnológica', grado:'6to Año', eje:'La reflexión sobre la tecnología, como proceso socio cultural: diversidad, cambios y continuidades', temas:['Los cambios socio-técnicos en la vida cotidiana y en los diversos procesos técnicos de trabajo.','La energía en distintos contextos y sus implicancias sociales y culturales.','Sistemas de control en procesos de la vida cotidiana y en las prácticas sociales, a lo largo de la historia.'] },

  { nivel:'Primario', materia:'Educación Tecnológica', grado:'7mo Año', eje:'Los procesos tecnológicos', temas:['El diseño en los productos y procesos tecnológicos. Momentos o fases en el proceso de resolución de problemas de diseño.','Los sistemas. Flujos de materia, energía e información. Interacción en las operaciones de los procesos.','La energía. Circuitos eléctricos simples: funcionamiento y elementos. El circuito en serie y en paralelo.','Los procesos de comunicación a distancia mediados por tecnologías.','Los sistemas de control automático: los sensores. Procesos de automatización.'] },
  { nivel:'Primario', materia:'Educación Tecnológica', grado:'7mo Año', eje:'Los medios técnicos', temas:['Los procesos de comunicación a distancia: las funciones de emisión, medio de transmisión y recepción.','Los procesos automáticos. La secuencia de acciones y decisiones humanas que han sido delegadas en artefactos programados.','La información en los sistemas de control automático: diagramas de bloques.','El diseño de estructuras y máquinas presentes en los procesos tecnológicos: variables, especificaciones y restricciones técnicas.','Bocetos y croquis como herramientas de trabajo y comunicación.'] },
  { nivel:'Primario', materia:'Educación Tecnológica', grado:'7mo Año', eje:'La reflexión sobre la tecnología, como proceso socio cultural: diversidad, cambios y continuidades', temas:['Los cambios socio-técnicos en el paso del control manual de los procesos a la automatización.','Los cambios en la organización de los procesos al articular las tecnologías de control y de comunicación: telecomunicaciones y robótica.','Los diversos cambios y continuidades en las prácticas sociales a partir del acceso masivo a las tecnologías de comunicación e información.','Las influencias, determinaciones, condicionamientos y aportes en las relaciones entre tecnologías, la sociedad, la cultura y el mercado.'] },

  // ══════════════════════════════════════════════════════════════════════════
  // LENGUA
  // ══════════════════════════════════════════════════════════════════════════

  { nivel:'Primario', materia:'Lengua', grado:'1er Año', eje:'En relación con la comprensión y la producción oral', temas:['Conversación informal y formal: Participación asidua en conversaciones espontáneas informales y formales, respetando las variedades dialectales.','Escucha comprensiva de textos narrativos (textos ficcionales y experiencias personales) y descripciones de objetos, animales y personas leídos o narrados por el docente y otros adultos.','La producción asidua de narraciones de experiencias personales, de anécdotas familiares y de descripciones.','La renarración, con distintos propósitos, de cuentos, fábulas y otros textos narrativos literarios.','La escucha, comprensión y disfrute de poesías, coplas, canciones, adivinanzas y otros géneros poéticos orales.','La escucha comprensiva de consignas de tarea escolar expresadas de manera clara y pertinente.'] },
  { nivel:'Primario', materia:'Lengua', grado:'1er Año', eje:'En relación con la lectura', temas:['La frecuentación y exploración asidua de variados materiales escritos, en distintos escenarios y circuitos de lectura.','La lectura (comprensión y disfrute) de textos literarios (cuentos, fábulas, leyendas, poesías, coplas, adivinanzas) y textos no literarios.','La lectura de palabras y de oraciones que conforman textos con abundantes ilustraciones y fragmentos de textos.'] },
  { nivel:'Primario', materia:'Lengua', grado:'1er Año', eje:'En relación con la escritura', temas:['La escritura asidua de textos en colaboración con el docente: discutir y consensuar el propósito, idear y redactar el texto conjuntamente.','La escritura de palabras y de oraciones que conforman un texto (afiches, epígrafes, mensajes, invitaciones, respuestas a preguntas).','Escritura en distintos formatos y soportes. Separación de palabras.'] },

  { nivel:'Primario', materia:'Lengua', grado:'2do Año', eje:'En relación con la comprensión y la producción oral', temas:['Conversación. Actos de habla (narrar, describir, pedir, dar opinión y justificarla). Turnos de intercambio y respeto por las intervenciones.','Escucha comprensiva de textos narrativos (ficionales y reales) y descriptivos leídos o expresados oralmente por adultos.','Producción de narraciones: Textos literarios (Cuentos, fábulas) de experiencias personales, anécdotas y descripciones.','La renarración de cuentos, fábulas y otros textos narrativos.','La escucha, comprensión y disfrute de poesías, coplas, canciones, adivinanzas y otros géneros poéticos orales.'] },
  { nivel:'Primario', materia:'Lengua', grado:'2do Año', eje:'En relación con la lectura', temas:['Escenarios y circuitos de lectura: Variedad de textos escritos. Portadores de textos (enciclopedias, libros de cuentos, diccionarios, diarios) y su función social.','La lectura compartida de cuentos, fábulas, leyendas, poesías, coplas, adivinanzas y textos no literarios.','La comprensión de textos instruccionales accesibles (recetas, instrucciones para elaborar un objeto, consignas escolares).','La lectura autónoma de palabras, de oraciones que conforman textos con abundantes ilustraciones.'] },
  { nivel:'Primario', materia:'Lengua', grado:'2do Año', eje:'En relación con la escritura', temas:['La escritura asidua de textos en colaboración con el docente.','El proceso de la escritura: Planificación, textualización y revisión de textos con un propósito comunicativo determinado.','El proceso de escritura de textos literarios y no literarios: Cuentos inventados, poesías, cartas, esquelas, epígrafes, diálogos.','Escritura autónoma de palabras y de oraciones que conforman textos. Utilización de distintos tipos de letras.'] },
  { nivel:'Primario', materia:'Lengua', grado:'2do Año', eje:'En relación con la reflexión sobre la lengua (sistema, norma y uso) y los textos', temas:['Palabras y expresiones para mejorar el vocabulario: Uso de sinónimos y antónimos en reformulaciones orales y escritas.','Elaboración de campos semánticos: Agrupación de palabras bajo criterios conceptuales y semánticos comunes.','El punto seguido y aparte. Uso de mayúsculas después del punto y en nombres propios.','Raya de diálogo y signos auxiliares: Uso y reconocimiento de la raya de diálogo.','Convenios ortográficos: mb – mp, nv, que – qui, gue – gui, uso de r y rr.','Grupos consonánticos: br – bl, cr – cl, dr, gr – gl, pr – pl, fr – fl, tr – tl.'] },

  { nivel:'Primario', materia:'Lengua', grado:'3er Año', eje:'En relación con la comprensión y la producción oral', temas:['La conversación formal e informal: Fórmulas de tratamiento en conversaciones formales.','Turnos de intercambio. Dramatización: Planificación grupal de tareas y juego dramático.','Propósitos comunicativos: Uso de la palabra para describir, pedir, opinar, justificar, complementar, ampliar o refutar lo dicho por otro.','La escucha, comprensión y disfrute de poesías, coplas, canciones, adivinanzas y otros géneros poéticos orales.'] },
  { nivel:'Primario', materia:'Lengua', grado:'3er Año', eje:'En relación con la lectura', temas:['Utilización de diferentes estrategias de lectura: Formulación de hipótesis, verificación, reformulación.','Comprensión del texto: Localización de información explícita e implícita, reconocimiento del orden cronológico y causal.','Comprensión de consignas: Identificación del objetivo, orden y jerarquía de las acciones en tareas escolares.','Diferentes modos de leer: Lecturas compartidas, individuales, en silencio y en voz alta frente a un auditorio.'] },
  { nivel:'Primario', materia:'Lengua', grado:'3er Año', eje:'En relación con la escritura', temas:['La escritura asidua de diversos textos: narraciones con descripción de personajes o ambientes y diálogos, cartas personales, notas de enciclopedia.','Construcción de familia de palabras: Reflexión ortográfica sobre palabras derivadas de una raíz común.','Sinónimos y antónimos: Uso en la sustitución de palabras escritas para evitar repeticiones.','Clasificación de palabras: Sustantivos comunes (concretos) y propios. Adjetivos (calificativos) y Verbos de acción.','Convenciones de la puesta en página: Uso de sangrías, márgenes, mayúsculas, signos de puntuación.'] },
  { nivel:'Primario', materia:'Lengua', grado:'3er Año', eje:'En relación con la reflexión sobre la lengua (sistema, norma y uso) y los textos', temas:['Signos de interrogación y exclamación: Diferenciación fónica y sentido que adquieren las oraciones.','Uso de mayúsculas: Normativa del uso de mayúsculas después del punto y en sustantivos propios.','Convenciones ortográficas: mb - mp, nr, z a ces, -aba del pretérito imperfecto, que - qui, gue - gui, diéresis, usos de la h.','Sílaba tónica: Identificación de la sílaba tónica de las palabras y su acentuación.'] },

  { nivel:'Primario', materia:'Lengua', grado:'4to Año', eje:'Comprensión y producción oral', temas:['Conversación. Tema. Contenido. Propósitos. Vocabulario acorde al contenido y respeto de turnos.','Escucha comprensiva y formulación oral de descripciones de personas, personajes, lugares, objetos y procesos.','La exposición: Producción individual y grupal sobre contenidos estudiados, respetando introducción, desarrollo y cierre.','Instrucciones seriadas: Consignas de tarea escolar y reglas de juego.','Producción de narraciones y renarraciones de historias no ficcionales.'] },
  { nivel:'Primario', materia:'Lengua', grado:'4to Año', eje:'Lectura y producción escrita', temas:['Lectura. Objetivos y portadores: Visitas periódicas a bibliotecas y abordaje de textos con propósitos diversos.','Paratexto: Índice, dedicatoria, prólogo, tabla de materias, ilustraciones, tipografías.','Estrategias de lectura: Consulta del paratexto, inferencias por contexto, campos semánticos y relectura.','Diccionario: Búsqueda y selección de acepciones convenientes según el texto.','Escritura: Planificación según la situación comunicativa. Borrador. Revisión y reformulación del escrito.','Escritura de diálogos, textos narrativos no ficcionales (biografías), cartas personales y exposiciones escritas.'] },
  { nivel:'Primario', materia:'Lengua', grado:'4to Año', eje:'Literatura', temas:['Literatura de tradición oral: Relatos, cuentos, fábulas, leyendas, coplas, romances y rondas de tradición regional.','Literatura de autor: Novela breve, cuentos, relatos, poesías, canciones, obras de teatro y títeres de autor.','Recursos propios del discurso literario: Descubrimiento de mundos creados y juegos con el lenguaje y los sonidos.','Relatos ficcionales. Renarraciones. Textos de invención.'] },
  { nivel:'Primario', materia:'Lengua', grado:'4to Año', eje:'Reflexión sobre la lengua (sistema, norma y uso) y los textos', temas:['Lenguas y variedades lingüísticas: Respeto y valoración de las variedades dialectales de la comunidad.','Clases de palabras: Sustantivos propios y comunes. El adjetivo calificativo. Concordancia de género y número.','El verbo. Tiempo pasado, presente y futuro.','Conectores temporales y causales propios de los textos narrativos.','Familia de palabras. Sufijos y prefijos: Diminutivos y aumentativos, prefijación y sufijación.','Separación de palabras en sílabas. Sílaba tónica. Clasificación en agudas, graves y esdrújulas. Reglas generales de acentuación.','Signos de puntuación: Punto y seguido, punto y aparte, coma en enumeraciones, dos puntos, paréntesis y raya de diálogo.'] },

  { nivel:'Primario', materia:'Lengua', grado:'5to Año', eje:'Comprensión y producción oral', temas:['Conversación. Tema. Contenido. Propósitos. Vocabulario preciso y argumentación de opiniones.','Escucha comprensiva y formulación oral de descripciones y exposiciones complejas.','La exposición: Preparación, presentación y uso de materiales de apoyo visuales.','Producción de narraciones, renarraciones, descripciones y exposiciones con material de apoyo sobre temas de estudio.'] },
  { nivel:'Primario', materia:'Lengua', grado:'5to Año', eje:'Lectura y producción escrita', temas:['Lectura. Objetivos. Portadores. Estrategias de lectura: Búsqueda y localización de información en diversas fuentes impresas y digitales.','Paratexto (prefacio, prólogo, apéndice, anexo, bibliografía, índice), inferencias y diccionario.','Resumen. Organizadores gráficos: El mapa conceptual como soporte para el estudio y exposiciones.','Escritura de textos no ficcionales: Narraciones con relaciones de causalidad y orden cronológico. Resúmenes y revistas escolares.','Cartas formales: Estructura, fórmulas de cortesía y adecuación al destinatario.'] },
  { nivel:'Primario', materia:'Lengua', grado:'5to Año', eje:'Literatura', temas:['Literatura de tradición oral: Mitos, leyendas, cuentos tradicionales, romances, coplas y rondas.','Literatura de autor: Novelas, antologías poéticas, cuentos de autor y obras teatrales de mayor extensión.','Recursos propios del discurso literario: Figuras retóricas, juegos sonoros, connotación y creación de sentidos.','Escritura de relatos ficcionales: Reescritura modificando el narrador o el marco espacio-temporal.'] },
  { nivel:'Primario', materia:'Lengua', grado:'5to Año', eje:'Reflexión sobre la lengua (sistema, norma y uso) y los textos', temas:['Lenguas y variedades lingüísticas presentes en la literatura y los medios de comunicación.','Formas de organización textual: El párrafo y la oración. Estructura interna de la oración (sujeto expreso y tácito).','Familia de palabras. Prefijos. Sufijos. Composición.','Sinónimos. Antónimos. Hiperónimos. Hipónimos: Red semántica y cohesión textual.','Clases de palabras: Sustantivo, adjetivo, artículo, verbo, adverbio y pronombres.','Reglas de acentuación: Palabras agudas, graves, esdrújulas y tilde diacrítica.','Tiempos verbales propios de la narración (pretérito perfecto simple, imperfecto, pluscuamperfecto) y conectores.','Reglas ortográficas básicas y de puntuación (uso de dos puntos en estilo directo, comas para aclaraciones, paréntesis).'] },

  { nivel:'Primario', materia:'Lengua', grado:'6to Año', eje:'Comprensión y producción oral', temas:['Conversación: Participación en debates sobre temas de estudio e interés general, manifestando opiniones, acuerdos y desacuerdos.','La entrevista: Preparación, elaboración de cuestionarios, fórmulas de tratamiento y toma de notas.','Exposiciones. Vocabulario apropiado y específico: Exposiciones grupales e individuales sobre temas complejos.','Producción de narraciones y renarraciones con inclusión de diálogos directos e indirectos.'] },
  { nivel:'Primario', materia:'Lengua', grado:'6to Año', eje:'Lectura y producción escrita', temas:['Lectura. Objetivos. Portadores. Estrategias de lectura: Abordaje de textos extensos y complejos. Propósito del autor e intertextualidad.','Resumen. Lectura frente a un auditorio: Fluidez, entonación y adecuación al público.','Escritura de textos no ficcionales: Planificación, puesta en texto, borrador, revisión y reformulación.','Narraciones con orden cronológico, causalidad, diálogos y descripciones: Escritura de biografías y relatos históricos.','Cartas formales con distintos propósitos y destinatarios: Cartas de lectores, solicitudes y reclamos.'] },
  { nivel:'Primario', materia:'Lengua', grado:'6to Año', eje:'Literatura', temas:['Obras literarias de tradición oral y de autor: Mitos, leyendas, cuentos, novelas, poesías, canciones y obras de teatro.','Recursos del discurso literario: Relaciones de intertextualidad, análisis del género y de indicios del texto.','Relatos ficcionales y nuevas versiones de narraciones literarias leídas o escuchadas.','Textos de invención: Priorización del juego con las palabras, sonidos y recursos poéticos.'] },
  { nivel:'Primario', materia:'Lengua', grado:'6to Año', eje:'Reflexión sobre la lengua (sistema, norma y uso) y los textos', temas:['Lenguas y variedades lingüísticas: Nociones de dialecto (geográfico y social) y registro.','Unidades lingüísticas, relaciones gramaticales y textuales: Coherencia y cohesión (deícticos, elipsis, referencia, conectores).','Clases de palabras: Sustantivo, adjetivo, artículo, verbo, adverbio, pronombres personales, posesivos y demostrativos.','Tiempos verbales propios de la narración (pretérito pluscuamperfecto, condicional) y conectores temporales/causales.','Presente para marcar atemporalidad y adjetivos descriptivos en textos expositivos.','Recursos cohesivos: Pronombres exclamativos e interrogativos, sinónimos, antónimos, hiperónimos, hipónimos.','Familias de palabras: Sufijación, prefijación y composición.'] },

  { nivel:'Primario', materia:'Lengua', grado:'7mo Año', eje:'Comprensión y producción oral', temas:['Conversación formal: Turnos de intercambio en discusiones sobre temas del área y de la cultura a partir de diversas fuentes.','Actos de habla directos e indirectos: Uso de deícticos temporales, espaciales y personales.','Escucha comprensiva y crítica de textos narrativos, expositivos y argumentativos orales, identificando posturas y justificaciones.','Exposición oral con soporte gráfico y sin soporte. Repertorio léxico específico.','La entrevista: Planificación, entrevistas grabadas, sistematización y posterior informe escrito.'] },
  { nivel:'Primario', materia:'Lengua', grado:'7mo Año', eje:'Lectura y producción escrita', temas:['El paratexto en distintos textos: Paratexto icónico (ilustraciones, gráficos, infografías) y verbal (epígrafes, prólogos, notas).','El texto narrativo. La crónica periodística: Diferenciación de crónicas según temática y recursos discursivos.','El texto expositivo. Relaciones intratextuales (definiciones, comparaciones, citas, ejemplos).','Las reseñas de libros y espectáculos en diarios y revistas de circulación social.','Estrategias de lectura y de escritura: Hipótesis, inferencias, relación de la información con conocimientos previos.','Resumen. Organizadores gráficos: El mapa conceptual para sistematizar relaciones jerárquicas y conceptuales.'] },
  { nivel:'Primario', materia:'Lengua', grado:'7mo Año', eje:'Literatura', temas:['Literatura de autores regionales, nacionales y universales: Cuentos maravillosos, realistas, fantásticos, de terror, de aventuras.','Novela: Comentarios de novelas extensas con tramas complejas, análisis de cambios en personajes, saltos temporales y voces.','Poemas y canciones. Las figuras literarias del género poético: Coplas ancestrales, romances y análisis de recursos sonoros.','Escritura de textos narrativos y poéticos de invención en situaciones de taller literario.','El texto dramático: Estructura de la obra teatral (actos, escenas, acotaciones, parlamentos). Teatro leído y representación teatral.'] },
  { nivel:'Primario', materia:'Lengua', grado:'7mo Año', eje:'Reflexión sobre la lengua (sistema, norma y uso) y los textos', temas:['Variedades lingüísticas: Dialecto (geográfico y social) y registro. Aportes de otras lenguas al español y usos locales en Salta.','El texto, el párrafo y la oración. Unidades lingüísticas y relaciones gramaticales y de cohesión en tramas argumentativas.','Géneros discursivos: Características de textos de opinión (tesis y argumentos), informativos, instruccionales y de divulgación.','Clases de palabras: Sustantivos, adjetivos, verbos, preposiciones, adverbios, artículos y pronombres. Palabras variables e invariables.','Sujeto expreso y desinencial. Construcción sustantiva (núcleo y modificadores).','Relaciones de significado: Sinónimos, antónimos, hiperónimos, hipónimos para la cohesión y estilo.','Reglas ortográficas y de puntuación: Puntuación de textos narrativos, de opinión y de diálogos (puntos suspensivos, comillas).'] },

  // ══════════════════════════════════════════════════════════════════════════
  // MATEMÁTICA
  // ══════════════════════════════════════════════════════════════════════════

  { nivel:'Primario', materia:'Matemática', grado:'1er Año', eje:'Geometría y Medida', temas:['Nociones Espaciales: Recorrido en el espacio próximo. Puntos de referencia. Relaciones de posición (arriba, abajo, adelante, atrás, derecha, izquierda).','Nociones Geométricas (Cuerpos): Formas (cúbica, cilíndrica, esférica, prisma de base rectangular, pirámide de base cuadrada) y sus características.','Nociones Geométricas (Figuras): Formas cuadrada, rectangular, triangular, circular. Reconocimiento, denominación y reproducción.','Composición, descomposición y transformación de figuras por medio de plegados y recortes.','Clasificación de figuras según lados curvos o rectos. Reconocimiento de líneas abiertas, cerradas, curvas, rectas, regiones y fronteras.','Mediciones: Nociones de longitud y distancia. Unidades no convencionales y convencionales (metro, medio metro y regla graduada).','Noción de masa y capacidad: Unidades no convencionales y convencionales de uso frecuente.','Noción de intervalo de tiempo: Uso del calendario (día, semana, mes, año) y noción de temperatura (frío, calor, tibio).'] },
  { nivel:'Primario', materia:'Matemática', grado:'1er Año', eje:'Número y Operaciones', temas:['Números: Sucesión natural y escrita hasta el 100. Funciones y usos sociales de los números.','Regularidades en la serie oral y escrita. Realización oral y registro escrito de conteo y sobre conteo.','Denominación oral y escrita de los números, cardinalidad, conteo con distintas escalas y estimación.','Comparación de colecciones según el número de elementos y agrupamiento de colecciones equivalentes.','Equivalencias entre los distintos órdenes (descomposición aditiva) y escrituras equivalentes de un número.','Encuadramiento de un número entre decenas y relación de orden (mayor, igual, menor, anterior, posterior).','Transformaciones que afectan la cardinalidad de una colección (agregar, reunir, quitar, separar, comparar, igualar).','Resolución de problemas con distintos significados de la suma y de la resta (campo aditivo).','Resolución de problemas con distintos significados de la multiplicación y división (campo multiplicativo).','Construcción de estrategias de cálculo mental y escrito (exacto y aproximado) utilizando sumas y restas.'] },

  { nivel:'Primario', materia:'Matemática', grado:'2do Año', eje:'Geometría y Medida', temas:['Nociones Espaciales: Relaciones de posición, de orientación y de dirección (horizontal, vertical, inclinada). Recorridos y trayectos.','Ubicación en el espacio de objetos y personas utilizando relaciones espaciales.','Nociones Geométricas (Cuerpos): Formas (cúbica, cilíndrica, esférica, prisma de base rectangular, tetraedro, pirámide de base cuadrada) y sus elementos.','Nociones Geométricas (Figuras): Elementos (vértice y lados) y descripción de figuras. Clasificación según el número de lados.','Líneas rectas y curvas (abiertas y cerradas). Posiciones de rectas (vertical, horizontal, inclinada) y ángulos como giros.','Mediciones: Relaciones de comparación, equivalencia y orden entre unidades de medida (metro, decímetro, centímetro, litro, kilogramo).','Lectura del calendario (día, mes, año) y del reloj (hora, media hora, cuarto de hora, minuto, segundo).'] },
  { nivel:'Primario', materia:'Matemática', grado:'2do Año', eje:'Número y Operaciones', temas:['Sucesión natural oral y escrita hasta 1.000. Funciones y usos sociales de los números.','Regularidades en la serie oral y escrita. Conteo y sobre conteo. Escritura de cantidades.','Equivalencias entre los distintos órdenes (descomposición aditiva). Análisis del valor de la cifra según su posición.','Encuadramiento de un número entre decenas y centenas. Relación de orden.','Transformaciones que afectan la cardinalidad de una colección (agregar, reunir, repartir, quitar, separar, comparar, igualar).','Resolución de problemas con distintos significados de la suma y resta, multiplicación y división.','Sumas, restas, multiplicación y división de números naturales de hasta dos y tres cifras.'] },

  { nivel:'Primario', materia:'Matemática', grado:'3er Año', eje:'Geometría y Medida', temas:['Nociones Espaciales: Puntos en un cuadriculado. Formas de orientación convencionales (puntos cardinales, brújula).','Relaciones de dirección: paralelismo y perpendicularidad. Realización y descripción de recorridos.','Nociones Geométricas (Cuerpos): Formas y sus elementos.','Nociones Geométricas (Figuras): Formas cuadrada, rectangular, triangular, circular (circunferencia y círculo). Clasificación.','Reconocimiento de regularidades en pisos, embaldosados, guardas y frisos.','Composición y descomposición de figuras. Rectas paralelas y perpendiculares. Uso de instrumentos de trazado.','Mediciones (Unidades convencionales): Metro, decímetro, centímetro, milímetro, litro, kilogramo y sus fracciones.','Medición del tiempo y temperatura: El reloj (hora, media hora, cuarto de hora) y el termómetro.'] },
  { nivel:'Primario', materia:'Matemática', grado:'3er Año', eje:'Número y Operaciones', temas:['Sucesión oral y escrita hasta 10.000. Funciones, usos sociales, conteo y denominación.','Sistema de numeración posicional: Unidad, decenas, centenas, unidades y decenas de mil. Equivalencias entre órdenes.','Análisis del valor de la cifra según la posición. Escrituras equivalentes de un número.','Encuadramiento de un número entre decenas, centenas y unidades de mil. Relación de orden.','Resolución de problemas con distintos significados de la suma y resta, multiplicación y división.','Algoritmos de multiplicación por una cifra y división. Cálculo mental y escrito exacto y aproximado.'] },

  { nivel:'Primario', materia:'Matemática', grado:'4to Año', eje:'Geometría y Medida', temas:['Relaciones Espaciales: Ubicación, orientación, posición respecto al sujeto como punto de referencia. Puntos en una línea y en el plano.','Cuerpos: Elementos y clasificación según propiedades (caras iguales, número de caras, vértices, aristas y ángulos).','Figuras: Elementos y clasificación de figuras según vértices, lados y ángulos.','Ángulos: Elementos y clasificación por su abertura (rectos, agudos, obtusos, llanos). Comparación, ordenación y clasificación.','Poligonales abiertas y cerradas. Trazado de rectas paralelas y perpendiculares con escuadra.','Movimientos: Noción de rotación, traslación y simetría. Figuras simétricas.','La circunferencia y el círculo: Elementos y uso del compás.','Triángulos: Clasificación por sus lados y sus ángulos.','Mediciones (Unidades convencionales): Metro, decímetro, centímetro, milímetro, kilómetro, litro, kilogramo, gramo y sus múltiplos y submúltiplos.','Medición de ángulos: el grado y el transportador. Perímetro de figuras.'] },
  { nivel:'Primario', materia:'Matemática', grado:'4to Año', eje:'Número y Operaciones', temas:['La sucesión natural hasta 100.000. Relaciones de orden (mayor, menor, igual, anterior, posterior, entre).','Reconocimiento, predicción y descripción de patrones numéricos y no numéricos.','Sistema de numeración posicional: Órdenes (unidades, decenas, centenas, unidades de mil, decenas de mil).','Las operaciones de suma, resta, multiplicación y división con números naturales.','Aplicación de algoritmos convencionales con multiplicador y divisor de dos dígitos.','Divisibilidad: números primos y compuestos. Descomposición en factores primos.','Fracciones: Significado, escrituras equivalentes, fracciones equivalentes y relaciones de orden.','Expresiones decimales (hasta dos cifras decimales): Usos, base posicional, ordenamiento, equivalencias y aproximación.','Estadística y probabilidad: Recolección de datos, organización en tablas y gráficos, e introducción a la probabilidad.'] },

  { nivel:'Primario', materia:'Matemática', grado:'5to Año', eje:'Geometría y Medida', temas:['Representación elemental del espacio en croquis, planos, maquetas. Lectura, interpretación y construcción.','Ubicación de puntos en el plano con coordenadas.','Cuerpos: Clasificación y descripción en base a sus propiedades geométricas.','Los cuerpos geométricos: Armado de un cubo y de un prisma a partir de patrones.','Polígonos: Elementos. Propiedades de los lados y ángulos de un triángulo. Cuadriláteros: Elementos y clasificación.','Técnicas de construcción de cuadriláteros y triángulos con regla y compás.','Propiedades de la suma de los ángulos interiores de un triángulo y propiedad triangular.','Alturas de un triángulo. Clasificación de figuras según sus ejes y centros de simetría.','Ángulos: Unidades convencionales del sistema sexagesimal (grado, minuto, segundo).','Perímetros y áreas: Medición del área de figuras de lados rectos. El metro cuadrado.'] },
  { nivel:'Primario', materia:'Matemática', grado:'5to Año', eje:'Número y Operaciones', temas:['La sucesión natural: Lectura, descripción, interpretación y construcción de diagramas y tablas.','Sistema de numeración posicional: Sistemas posicional y no posicional (maya, griego, romano, decimal). Noción de base, valor relativo y absoluto.','Operaciones de suma, resta, multiplicación y división con números naturales. mcm y dcm en la resolución de problemas.','Potencias cuadradas y cúbicas de los números dígitos. Tablas de potencia.','Fracciones: Significado, relaciones de orden, fracciones equivalentes, representación en la recta y operaciones.','Expresiones decimales (hasta dos cifras): Usos, ordenamiento, representación en la recta y equivalencias con fracciones.','Proporcionalidad: Significado, relaciones de proporcionalidad directa e inversa.','Estadística y probabilidad: Recolección y organización de datos, gráficos y situaciones de azar.'] },

  { nivel:'Primario', materia:'Matemática', grado:'6to Año', eje:'Geometría y Medida', temas:['Representación elemental del espacio en croquis, planos, mapas y maquetas con factores de escala sencillos.','Ubicación de puntos en la recta y el plano con coordenadas.','Cuerpos geométricos: Armado de pirámides. Noción de congruencia y semejanza de figuras y cuerpos.','Ampliación y reducción de figuras. Traslación de un ángulo con regla y compás.','Polígonos: Clasificación, suma de los ángulos interiores de cualquier polígono. La mediatriz.','Construcción de triángulos y paralelogramos. Bisectriz de un ángulo.','Mediciones: Múltiplos y submúltiplos de metros, gramos y litros. Perímetros y áreas.','Área (unidades convencionales): Kilómetro cuadrado, metro cuadrado, centímetro cuadrado.','Deducción de fórmulas y cálculo de área de rectángulos, triángulos, rombos y trapecios.','Volumen de un cuerpo: Comparación y equivalencias de cuerpos.'] },
  { nivel:'Primario', materia:'Matemática', grado:'6to Año', eje:'Número y Operaciones', temas:['La sucesión natural: Usos y propiedades. Números en la recta numérica. Patrones numéricos.','Sistema de numeración posicional: Órdenes hasta unidades de millón.','Operaciones de suma, resta, multiplicación y división con números naturales (automatización con factores y divisores polidígitos).','Resolución de problemas de divisibilidad: números primos y compuestos, descomposición en factores primos, dcm, mcm y criterios de divisibilidad.','Análisis de tablas de potencia cuadrada y raíces cuadradas exactas.','Fracciones: Significado, escrituras equivalentes, fracciones equivalentes (amplificación y simplificación) y relación de orden.','Operaciones con fracciones: Suma, resta, multiplicación y división de fracciones.','Suma, resta, multiplicación y división de expresiones decimales. Redondeo y truncamiento.','Proporcionalidad directa e inversa: Propiedades y expresiones usuales (porcentaje, escala, interés).','Estadística y probabilidad: Recolección de datos, tablas, pictogramas, diagramas de barras, circulares e interpretación de información.'] },

  { nivel:'Primario', materia:'Matemática', grado:'7mo Año', eje:'Geometría y Medida', temas:['Sistemas de referencia para la ubicación de puntos en el plano. Coordenadas cartesianas y en la esfera terrestre.','Cuerpos: poliedros y redondos. Elementos, propiedades, relaciones entre ellos y reproducción de cuerpos.','Movimientos: simetrías, traslaciones y rotaciones en el plano y sus propiedades.','Lugar geométrico: circunferencias, mediatrices, bisectrices.','Posiciones relativas entre rectas y entre planos en el espacio. Ángulos entre paralelas.','Área: equivalencia de figuras. Volumen: comparación, ordenamiento y cálculo de volúmenes de prismas.','Equivalencia de expresiones de cantidad utilizando unidades del SIMELA.'] },
  { nivel:'Primario', materia:'Matemática', grado:'7mo Año', eje:'Número y Operaciones', temas:['Números Naturales: orden. Sistema de Numeración Posicional (decimal, sexagesimal, binario). Base, valor relativo, el cero.','Cálculo exacto y aproximado, mental, escrito y con calculadora.','Operaciones con números naturales, combinatoria y estrategias para el recuento de casos.','Utilización de las jerarquías y propiedades de las operaciones (reglas del uso de paréntesis).','Notación científica para expresar y comparar números muy grandes o muy pequeños.','Algoritmos de Euclides. Criba de Eratóstenes. mcm y dcm. Números primos, coprimos, amigos, perfectos.','Utilización de potencias y raíces para la resolución de problemas de áreas y volúmenes.','Números racionales positivos: usos, escritura fraccionaria y decimal. Cuatro operaciones básicas con racionales.','Proporcionalidad: Razón y proporción numérica directa e inversa. Repartición proporcional, escala, tasa y porcentaje.'] },
  { nivel:'Primario', materia:'Matemática', grado:'7mo Año', eje:'Álgebra y Funciones', temas:['Patrones numéricos. Generalización. Determinación de la regla de formación de patrones numéricos.','Expresiones algebraicas: Igualdades, ecuaciones y fórmulas. Significado.','Distintas formas de representación de funciones (tablas, fórmulas, coloquial, gráfica). Dependencia funcional.','Funciones numéricas: lineal (caso particular, función directamente proporcional) e inversa. Gráficas y sus características.'] },
  { nivel:'Primario', materia:'Matemática', grado:'7mo Año', eje:'Probabilidad y Estadística', temas:['Nociones elementales de estadística: población y muestras (representatividad).','Parámetros estadísticos: media aritmética, moda, mediana (significado y uso).','Interpretación y construcción de tablas y gráficos (pictogramas, diagramas de barras, gráficos circulares, de línea, de puntos).','Fenómenos aleatorios: Comparación de probabilidades de diferentes sucesos (seguros, imposibles, poco probables).','Cálculo combinatorio mediante construcción de diagramas arbolados para determinación de espacios muestrales. Azar.'] },
]

// ─────────────────────────────────────────────────────────────────────────────
// Seeder logic
// ─────────────────────────────────────────────────────────────────────────────

async function seed() {
  console.log(`Seeding ${DATA.length} curriculum rows (Nivel Primario)...`)
  let inserted = 0
  let skipped = 0
  let errors = 0

  for (const entry of DATA) {
    try {
      await sql`
        INSERT INTO curriculum (jurisdiccion, nivel, materia, grado, eje, temas)
        VALUES (
          ${entry.jurisdiccion ?? DEFAULT_JURISDICTION},
          ${entry.nivel},
          ${entry.materia},
          ${entry.grado},
          ${entry.eje},
          ${JSON.stringify(entry.temas)}::jsonb
        )
      `
      inserted++
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err)
      if (msg.includes('duplicate') || msg.includes('unique')) {
        skipped++
      } else {
        errors++
        console.error(`  ✗ [${entry.materia} / ${entry.grado} / ${entry.eje.slice(0, 40)}]: ${msg}`)
      }
    }
  }

  console.log(`\n✅ Done.`)
  console.log(`   Inserted : ${inserted}`)
  console.log(`   Skipped  : ${skipped}  (duplicate rows)`)
  console.log(`   Errors   : ${errors}`)
  process.exit(0)
}

seed().catch((err) => {
  console.error('Seeder failed:', err)
  process.exit(1)
})

